### ISSUE TITLE
Does this work with Aria2?

### ISSUE THREAD

**Issue by Yankees4life** [bemble/holerr#5]
I know this is supposed to be used with Synology but I would like to know whether or not it works with aria2 and how to configure it to work with it

**Comment by bemble** [comment]
Hi,
Thanks for your interest and your question.
As is it, it won't work with `aria2`. It should be possible to make it works with `aria2`, but you must be able to download real-debrid files using `aria2`. I will give a try in few days :)

**Comment by Yankees4life** [comment]
> Hi, Thanks for your interest and your question. As is it, it won't work with `aria2`. It should be possible to make it works with `aria2`, but you must be able to download real-debrid files using `aria2`. I will give a try in few days :)

Downloading from real-debrid is possible to do. Aria2 is a very powerful download manager. I do like the prospect of this tool as it uses Go. Unfortunately, I can't afford a NAS system to use download station 🤣😂

**Comment by Yankees4life** [comment]
Any progress on this, mate?

**Comment by bemble** [comment]
> Any progress on this, mate?

It's been a while, and this is definitely something I will add soon (because I need it 😅).
I moved from Go to Python, adding Aria2 should be easier.
